-- MySQL Script generated by MySQL Workbench
-- Sat May 25 11:59:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema exosqlPlus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exosqlPlus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exosqlPlus` DEFAULT CHARACTER SET latin1 ;
USE `exosqlPlus` ;

-- -----------------------------------------------------
-- Table `exosqlPlus`.`acteurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exosqlPlus`.`acteurs` ;

CREATE TABLE IF NOT EXISTS `exosqlPlus`.`acteurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nom` CHAR(32) NOT NULL DEFAULT '',
  `Prenom` CHAR(32) NULL DEFAULT '',
  `DateNaissance` DATE NULL DEFAULT NULL,
  `Pays` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `exosqlPlus`.`realisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exosqlPlus`.`realisateur` ;

CREATE TABLE IF NOT EXISTS `exosqlPlus`.`realisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nom` CHAR(32) NULL DEFAULT '',
  `Prenom` CHAR(32) NULL DEFAULT '',
  `DateNaissance` DATE NULL DEFAULT NULL,
  `NombreFilm` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `exosqlPlus`.`film`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exosqlPlus`.`film` ;

CREATE TABLE IF NOT EXISTS `exosqlPlus`.`film` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Titre` CHAR(64) NULL,
  `Genre` VARCHAR(32) NULL DEFAULT NULL,
  `Pays` VARCHAR(16) NULL DEFAULT NULL,
  `AnneeSortie` INT(11) NULL DEFAULT NULL,
  `Budget` INT(11) NULL DEFAULT NULL,
  `realisateur_id` INT NOT NULL,
  PRIMARY KEY (`id`, `realisateur_id`),
  INDEX `fk_film_realisateur1_idx` (`realisateur_id` ASC),
  CONSTRAINT `fk_film_realisateur1`
    FOREIGN KEY (`realisateur_id`)
    REFERENCES `exosqlPlus`.`realisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `exosqlPlus`.`acteurs_has_film`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exosqlPlus`.`acteurs_has_film` ;

CREATE TABLE IF NOT EXISTS `exosqlPlus`.`acteurs_has_film` (
  `acteurs_id` INT NOT NULL,
  `film_id` INT NOT NULL,
  `SalaireActeur` INT(11) NULL,
  `RoleActeur` VARCHAR(64) NULL,
  PRIMARY KEY (`acteurs_id`, `film_id`),
  INDEX `fk_acteurs_has_film_film1_idx` (`film_id` ASC),
  INDEX `fk_acteurs_has_film_acteurs1_idx` (`acteurs_id` ASC),
  CONSTRAINT `fk_acteurs_has_film_acteurs1`
    FOREIGN KEY (`acteurs_id`)
    REFERENCES `exosqlPlus`.`acteurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acteurs_has_film_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `exosqlPlus`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
